name: Validate Auto-Fix PR

on:
  pull_request:
    types: [opened]

jobs:
  validate-fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: |
          pwd
          find . -type f

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Compile Python files
        run: |
          python -m compileall .

      - name: Run application
        run: |
          python <CORRECT_PATH_TO_MAIN.py>
